service:
  name: serverless-typescript-starter

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
          integration: lambda
